### ISSUE TITLE
undefined symbol: heif_check_filetype

### ISSUE THREAD

**Issue by Djoe689** [Cykooz/cykooz.heif#2]
Hi,
Running on Debian10, here below my the error:

```
root@t1:/usr/src/libheif#` python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cykooz.heif.image import RawHeifImage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cykooz/heif/image.py", line 9, in <module>
    from cykooz.heif.rust_heif import (
ImportError: /usr/local/lib/python3.7/dist-packages/cykooz/heif/rust_heif.cpython-37m-x86_64-linux-gnu.so: undefined symbol: heif_check_filetype
```

- libheif and libde265 compilation in /usr/src without issue (=> for debian user, uninstall libheif-dev from official repository)
- rustc installation without issue (=> for debian user, don't use the rustc from official repository, install the last version of rustc)

To install cykooz.heif (without issue):
```
# export RUSTFLAGS='-L /usr/src/libheif/libheif/.libs -L /usr/src/libde265/libde265/.libs/'
# pip3 install --force-reinstall --no-cache-dir cykooz.heif
Collecting cykooz.heif
  Downloading https://files.pythonhosted.org/packages/de/2f/b4ececebec346edba12e2a238f75f9b201cc6994fa3820c429e32ad1f358/cykooz.heif-0.10.2.tar.gz
Installing collected packages: cykooz.heif
  Found existing installation: cykooz.heif 0.10.2
    Uninstalling cykooz.heif-0.10.2:
      Successfully uninstalled cykooz.heif-0.10.2
  Running setup.py install for cykooz.heif ... done
Successfully installed cykooz.heif-0.10.2
```

Thank you for all!

**Comment by Djoe689** [comment]
The issue is here:
```
# ldd /usr/local/lib/python3.7/dist-packages/cykooz/heif/rust_heif.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffce4fb2000)
	libheif.so.1 => /lib/x86_64-linux-gnu/libheif.so.1 (0x00007fe41814f000)
.../...
```

The link is not done on my new libheif.so.1.10.0 but on the official debian libheif...

**Comment by Djoe689** [comment]
```
root@tour1:/usr/src/libheif# export LD_LIBRARY_PATH=/usr/src/libheif/libheif/.libs
root@tour1:/usr/src/libheif# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cykooz.heif.image import RawHeifImage
>>> 
```

Solved! You can close this issue, sorry...
